# fly.toml app configuration file generated for australia-bsb on 2025-07-09T15:55:54+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'australia-bsb'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
