name: Sync Bank List and Database

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    name: Build + Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Sync gem
        run: |
          bundle install
          bundle exec rake bsb:sync
          git config --global user.name ${GITHUB_USER_NAME}
          git config --global user.email ${GITHUB_EMAIL}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "fix: Sync update on $(date)"
          git push

