name: Sync Bank List and Database

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    name: Build + Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Sync gem
        run: |
          bundle install
          bundle exec rake bsb:sync
          git config user.name ${GITHUB_USER_NAME}
          git config user.email ${GITHUB_EMAIL}
          git add .
          git commit -m "fix: Sync update on $(date)"
          git push

